### ISSUE TITLE
Favicon fixen

### ISSUE THREAD

**Issue by emzudemo** [MalteRei/wirvsvirus-hackathon-spendensport#14]
Ein Favicon soll eingebunden werden.

![favicon](https://user-images.githubusercontent.com/13338334/77642539-1d746e00-6f5e-11ea-979b-0362d92fad4d.png)

**Comment by kaisnb** [comment]
Hab ein Pull-Request dazu erstellt. Habe nur leider vergessen es mit dem Issue zu verknüpfen. Schön wäre noch wenn du das Icon in 512x512 liefern könntest da Angular das Icon noch in diversen größen benötigt (512px ist die größte, die anderen kann ich mir daraus erstellen) für das PWA Feature. Z.B. wird bei einer PWA der Splashscreen erzeugt aus der angegebenen Farbe in der webmanifest und dem angegebenen Icon. Das Icon darf natürlich auch gern von dem favicon abweichen. Die Icons in der webmanifest werden dann auch verwendet wenn man das "Add to Homescreen" Feature der PWA verwendet. Ist das Projekt eigentlich schon irgendwo deployed?

**Comment by MalteRei** [comment]
Kannst du dir die benötigten Größen auch aus einem svg erstelen? Wenn ja habe ich es im Ordner Logo im root directory hochgeladen.

**Comment by kaisnb** [comment]
Jep hab das SVG entsprechend hoch skaliert und dann zu png konvertiert. Pull-Request ist raus. Das issue hier kann dann denke ich geclosed werden.

**Comment by MalteRei** [comment]
@kaisnb wir haben jeden Donnerstag und Dienstag ein Statusmeeting. Willst du dabei sein?

**Comment by kaisnb** [comment]
Hi, danke für die Einladung. Heute habe ich leider keine Zeit, aber in Zukunft vielleicht. Cool wäre auf jeden Fall wenn ihr das ganze für die Community transparenter gestaltet indem ihr hier mehr Issues anlegt, die Boards nutzt, Meilensteine definiert und hier noch die restlichen Materialien wie Screen Designs etc. uploaded. Dann wird der Einstieg für neue Contributer deutlich erleichtert. Weiter so!
Gruß Kai

**Comment by MalteRei** [comment]
Schade. Wenn du in der Zukunft beim meeting dabei sein willst kannst du am Besten eine EMail an team@gobonsai.org schreiben.
Danke für die Rückmeldung bezüglich der Transparenz. Wir nehmen es uns zu Herzen.
